# Generated by Django 4.2.6 on 2023-10-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_process', 'В обработке')], default='new', max_length=20),
        ),
    ]
